#ifndef PATCHWORK_GAME_SETUPS_HPP
#define PATCHWORK_GAME_SETUPS_HPP

#include "game_setup.hpp"
#include "generated/game_setups.hpp"

namespace patchwork {

/// Return the canonical GameSetup for the given ID.
///
/// The canonical setups are pre-generated by `codegen/generate_setups.R` and
/// stored as `constexpr` string literals in `cpp/generated/game_setups.hpp`.
/// `id` is wrapped into `[0, kNumGameSetups)` so any non-negative integer is valid.
[[nodiscard]] inline GameSetup make_setup(int id) {
    int idx = id % static_cast<int>(kNumGameSetups);
    if (idx < 0) idx += static_cast<int>(kNumGameSetups);
    return GameSetup(kGameSetups[static_cast<std::size_t>(idx)]);
}

}  // namespace patchwork

#endif  // PATCHWORK_GAME_SETUPS_HPP
