#!/usr/bin/env Rscript
# Generate src/generated/patches.hpp from data/patches.yaml
#
# Usage: Rscript codegen/generate_patches.R
#   Run from the project root directory.

library(yaml)

catalog <- yaml::read_yaml("data/patches.yaml")
stopifnot(length(catalog) == 33)

# Parse ASCII art shape into list of (row, col) offsets
parse_shape <- function(shape_str) {
  rows <- strsplit(trimws(shape_str, which = "right"), "\n")[[1]]
  # Verify rectangular
  lengths <- nchar(rows)
  stopifnot(length(unique(lengths)) == 1)

  cells <- list()
  for (r in seq_along(rows)) {
    chars <- strsplit(rows[r], "")[[1]]
    for (c in seq_along(chars)) {
      if (chars[c] == "X") {
        cells <- c(cells, list(c(r - 1L, c - 1L)))
      }
    }
  }
  cells
}

# Build output
lines <- character()
add <- function(...) lines <<- c(lines, paste0(...))

add("// AUTO-GENERATED by codegen/generate_patches.R — DO NOT EDIT")
add("// Source: data/patches.yaml")
add("")
add("#ifndef PATCHWORK_GENERATED_PATCHES_HPP")
add("#define PATCHWORK_GENERATED_PATCHES_HPP")
add("")
add("#include <array>")
add("#include <cstdint>")
add("")
add("namespace patchwork {")
add("")
add("struct CellOffset {")
add("    std::int8_t row;")
add("    std::int8_t col;")
add("};")
add("")
add("struct PatchData {")
add("    int id;")
add("    int buttons;")
add("    int time;")
add("    int income;")
add("    int num_cells;")
add("    std::array<CellOffset, 8> cells;  // max 8 cells per patch; unused entries are {0,0}")
add("};")
add("")
add("inline constexpr std::array<PatchData, 33> kPatches = {{")

for (i in seq_along(catalog)) {
  p <- catalog[[i]]
  cells <- parse_shape(p$shape)
  n <- length(cells)

  # Format cells array, pad to 8
  cell_strs <- vapply(cells, function(c) sprintf("{%d, %d}", c[1], c[2]), character(1))
  while (length(cell_strs) < 8) {
    cell_strs <- c(cell_strs, "{0, 0}")
  }
  cells_init <- paste(cell_strs, collapse = ", ")

  comma <- if (i < length(catalog)) "," else ""
  add(sprintf("    {%d, %d, %d, %d, %d, {%s}}%s",
              p$id, p$buttons, p$time, p$income, n, cells_init, comma))
}

add("}};")
add("")
add("static_assert(kPatches.size() == 33, \"Expected exactly 33 patches\");")
add("")
add("}  // namespace patchwork")
add("")
add("#endif  // PATCHWORK_GENERATED_PATCHES_HPP")

output_path <- "src/generated/patches.hpp"
dir.create(dirname(output_path), showWarnings = FALSE, recursive = TRUE)
writeLines(lines, output_path)
cat("Generated", output_path, "\n")
