#!/usr/bin/env Rscript
# Generate src/generated/game_setups.hpp from data/patches.yaml
#
# Usage: Rscript codegen/generate_setups.R
#   Run from the project root directory.
#
# The number of setups is controlled by the named constant N_SETUPS.
# Increasing N_SETUPS and re-running the script leaves the first 100 entries
# bit-for-bit identical, because each setup i uses set.seed(i) independently.

library(yaml)

N_SETUPS <- 100L

catalog <- yaml::read_yaml("data/patches.yaml")
stopifnot(length(catalog) == 33L)

names_vec <- vapply(catalog, function(p) p$name, character(1))
stopifnot(length(unique(names_vec)) == 33L)
stopifnot(all(nchar(names_vec) == 1L))

# The two-square tile ("2") is always placed last in the circle.
two_name <- "2"
two_idx <- which(names_vec == two_name)
stopifnot(length(two_idx) == 1L)
other_names <- names_vec[-two_idx]  # 32 names to shuffle

setups <- character(N_SETUPS)
for (i in seq_len(N_SETUPS)) {
  set.seed(i)
  perm <- sample(length(other_names))
  circle_str <- paste0(c(other_names[perm], two_name), collapse = "")
  stopifnot(nchar(circle_str) == 33L)
  stopifnot(substr(circle_str, 33L, 33L) == two_name)
  setups[[i]] <- circle_str
}

# Verify all setups are valid permutations of the 33 patch names
names_sorted <- sort(names_vec)
for (s in setups) {
  stopifnot(identical(sort(strsplit(s, "")[[1]]), names_sorted))
}

# ---------------------------------------------------------------------------
# Write header
# ---------------------------------------------------------------------------

lines <- character()
add <- function(...) lines <<- c(lines, paste0(...))

add("// AUTO-GENERATED by codegen/generate_setups.R — DO NOT EDIT")
add("// Source: data/patches.yaml")
add("")
add("#ifndef PATCHWORK_GENERATED_GAME_SETUPS_HPP")
add("#define PATCHWORK_GENERATED_GAME_SETUPS_HPP")
add("")
add("#include <array>")
add("#include <string_view>")
add("")
add("namespace patchwork {")
add("")
add("inline constexpr std::size_t kNumGameSetups = ", N_SETUPS, ";")
add("")
add("constexpr std::array<std::string_view, kNumGameSetups> kGameSetups = {{")

for (i in seq_len(N_SETUPS)) {
  comma <- if (i < N_SETUPS) "," else ""
  add('    "', setups[[i]], '"', comma)
}

add("}};")
add("")
add("static_assert(kGameSetups.size() == kNumGameSetups,")
add('              "kGameSetups must have kNumGameSetups entries");')
add("")
add("}  // namespace patchwork")
add("")
add("#endif  // PATCHWORK_GENERATED_GAME_SETUPS_HPP")

output_path <- "src/generated/game_setups.hpp"
dir.create(dirname(output_path), showWarnings = FALSE, recursive = TRUE)
writeLines(lines, output_path)
cat("Generated", output_path, "\n")
